 query{ 
     search(query:"timrwood", type:USER, first: 10) {
         nodes {
             ...on User {
                 issues(last:100, orderBy: field:CREATED_AT, direction:DESC) {
                     pageInfo { 
                         hasNextPage
                         endCursor
                    }
                    totalCount
                    nodes {
                        closed
                        reactions(last:100) {
                            nodes {
                                content
                            }
                        }
                        repository {
                            primaryLanguage{
                                name
                            }
                        }
                    }
                }
            }
        }
    }
}